
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "AREAS ATRIBUTO ATRIBUTOS LANGUAGE LANGUAGES NL TEXTDict : EntradasC NLEntradasC : EntradasC NL EntradaCEntradasC : EntradaCEntradaC : Areas LinguasAreas : AREAS Text NLAreas : Text : TEXTText : Linguas : LANGUAGES NL DictLinguasDictLinguas : DictLinguas DictLinguaDictLinguas : DictLinguaDictLingua : LANGUAGE NL DictTermosDictTermos : DictTermos DictTermoDictTermos : DictTermoDictTermo : '#' TEXT NL AtributosAtributos : Atributos AtributoAtributos : Atributo : ATRIBUTOS As NLAs : As ATRIBUTOAs : ATRIBUTO"
    
_lr_action_items = {'AREAS':([0,6,],[5,5,]),'LANGUAGES':([0,4,6,13,],[-6,8,-6,-5,]),'$end':([1,6,],[0,-1,]),'NL':([2,3,5,7,8,9,10,11,14,15,16,17,19,20,22,23,24,25,26,28,29,30,31,],[6,-3,-8,-4,12,13,-7,-2,-9,-11,18,-10,-12,-14,-13,24,-17,-15,-16,30,-20,-18,-19,]),'TEXT':([5,21,],[10,23,]),'LANGUAGE':([12,14,15,17,19,20,22,24,25,26,30,],[16,16,-11,-10,-12,-14,-13,-17,-15,-16,-18,]),'#':([18,19,20,22,24,25,26,30,],[21,21,-14,-13,-17,-15,-16,-18,]),'ATRIBUTOS':([24,25,26,30,],[-17,27,-16,-18,]),'ATRIBUTO':([27,28,29,31,],[29,31,-20,-19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Dict':([0,],[1,]),'EntradasC':([0,],[2,]),'EntradaC':([0,6,],[3,11,]),'Areas':([0,6,],[4,4,]),'Linguas':([4,],[7,]),'Text':([5,],[9,]),'DictLinguas':([12,],[14,]),'DictLingua':([12,14,],[15,17,]),'DictTermos':([18,],[19,]),'DictTermo':([18,19,],[20,22,]),'Atributos':([24,],[25,]),'Atributo':([25,],[26,]),'As':([27,],[28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Dict","S'",1,None,None,None),
  ('Dict -> EntradasC NL','Dict',2,'p_1','medicina_yacc.py',5),
  ('EntradasC -> EntradasC NL EntradaC','EntradasC',3,'p_3','medicina_yacc.py',8),
  ('EntradasC -> EntradaC','EntradasC',1,'p_4','medicina_yacc.py',11),
  ('EntradaC -> Areas Linguas','EntradaC',2,'p_5','medicina_yacc.py',14),
  ('Areas -> AREAS Text NL','Areas',3,'p_10','medicina_yacc.py',17),
  ('Areas -> <empty>','Areas',0,'p_11','medicina_yacc.py',20),
  ('Text -> TEXT','Text',1,'p_12','medicina_yacc.py',23),
  ('Text -> <empty>','Text',0,'p_13','medicina_yacc.py',26),
  ('Linguas -> LANGUAGES NL DictLinguas','Linguas',3,'p_14','medicina_yacc.py',29),
  ('DictLinguas -> DictLinguas DictLingua','DictLinguas',2,'p_15','medicina_yacc.py',32),
  ('DictLinguas -> DictLingua','DictLinguas',1,'p_16','medicina_yacc.py',35),
  ('DictLingua -> LANGUAGE NL DictTermos','DictLingua',3,'p_17','medicina_yacc.py',38),
  ('DictTermos -> DictTermos DictTermo','DictTermos',2,'p_18','medicina_yacc.py',41),
  ('DictTermos -> DictTermo','DictTermos',1,'p_19','medicina_yacc.py',44),
  ('DictTermo -> # TEXT NL Atributos','DictTermo',4,'p_20','medicina_yacc.py',47),
  ('Atributos -> Atributos Atributo','Atributos',2,'p_21','medicina_yacc.py',50),
  ('Atributos -> <empty>','Atributos',0,'p_22','medicina_yacc.py',53),
  ('Atributo -> ATRIBUTOS As NL','Atributo',3,'p_23','medicina_yacc.py',56),
  ('As -> As ATRIBUTO','As',2,'p_24','medicina_yacc.py',59),
  ('As -> ATRIBUTO','As',1,'p_25','medicina_yacc.py',62),
]
